name: Build Pack

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Separate pack files
        run: >-
          mkdir pose && mv
          README.md
          LICENSE
          assets/
          pack.mcmeta
          pack.png
          pose

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: POSE
          path: ${{ github.workspace }}/pose
